"""Template for the per-universe universe.yaml config file."""

from __future__ import annotations

UNIVERSE_YAML_TEMPLATE = """\
# Universe configuration -- tuneable without code changes.
# Generated by token-world scaffold; do not delete `universe_seed` once set.

universe_seed: {seed}  # Determinism anchor; never regenerate for an existing universe.

engine:
  max_chain_depth: 10         # GAP-ENG18 -- max chain depth before truncation
  classifier_min_confidence: 0.6  # D-07 -- classifier verdicts below this return low_confidence
"""


def render_universe_yaml(*, universe_seed: int) -> str:
    """Render the universe.yaml template with the given seed."""
    return UNIVERSE_YAML_TEMPLATE.format(seed=universe_seed)
